version: '1.0'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: geonames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
    networks:
      - db_conn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: address-correction-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - db_conn
    depends_on:
      db:
        condition: service_healthy
    tty: true
  sonarqube:
    profiles:
      - donotstart
    image: sonarqube:latest
    container_name: sonar-qube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    ports:
      - "9000:9000"
networks:
  db_conn:
    driver: bridge
