name: Continuous Integration Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn --batch-mode package

      - name: Rename the artifact
        run: cp target/CorrectAnAdreess-0.1.jar backend.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: backend
          path: backend.jar


  fake-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: backend

      - name: Fake Deploy
        run: ls backend*.jar




